### ISSUE TITLE
NPE when starting Server

### ISSUE THREAD

**Issue by victornoel** [waarp/WaarpGatewayFtp#28]
Hi,

I'm trying to run the Gateway FTP and when I start it I get the following NPE:
```
Exception in thread "main" java.lang.NullPointerException
	at org.waarp.gateway.ftp.config.FileBasedConfiguration.loadServerParam(FileBasedConfiguration.java:817)
	at org.waarp.gateway.ftp.config.FileBasedConfiguration.setConfigurationServerFromXml(FileBasedConfiguration.java:1323)
	at org.waarp.gateway.ftp.ExecGatewayFtpServer.initialize(ExecGatewayFtpServer.java:76)
	at org.waarp.gateway.ftp.ExecGatewayFtpServer.main(ExecGatewayFtpServer.java:58)
```

It looks like loadServerParam(), called by FileBasedConfiguration.setConfigurationServerFromXml() is expecting the variable httpExecutor to be non-null, but httpExecutor is initialised in configureHttps() which is called by ExecGatewayFtpServer.initialize() AFTER FileBasedConfiguration.setConfigurationServerFromXml() is called.

Is there a bug or am I missing something? I used the example configuration that I updated to fix problems in scripts (for example the wrong class is given to java in example/bin/ggserver.sh) and changed paths.

Thanks

**Comment by fredericBregier** [comment]
Hi,

Please could you give a try to the beta3 available from here?

http://sourceforge.net/projects/waarp/files/AllJars/AllJarsWaarpGatewayFtp-3.0.2-beta3.zip/download

There were several issues on Gateway Ftp 3.0.1 that were discovered not so long.
We have to enforce our validation tests... :-(

This is still a beta version, but this times it passes all our tests.

**Comment by victornoel** [comment]
Hi, the NPE is solved, but then I get this error:
```
Exception in thread "main" java.net.SocketException: Permission denied
	at sun.nio.ch.Net.bind(Native Method)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:124)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:59)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:125)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:522)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1196)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeBindNow(ChannelHandlerInvokerUtil.java:108)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeBind(DefaultChannelHandlerInvoker.java:214)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:208)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:1003)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:216)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:322)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:356)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:703)
	at java.lang.Thread.run(Thread.java:662)
```

**Comment by fredericBregier** [comment]
It is a simple one (or should be): for port < 1024, you must be administrator (root on Unix) to be able to launch the Ftp server to listen to port 21.
You can change the port for something else in the xml configuration:

    <network>
        <serverport>value</serverport> 
        <portmin>10000</portmin> 
        <portmax>30000</portmax>
    </network>

**Comment by fredericBregier** [comment]
@victornoel Does changing the server command port fix the issue?

**Comment by victornoel** [comment]
Sorry, I didn't get the opportunity to test before: yes it works, it wasn't clear because the property serverport wasn't present in the config file :)
Now I have problems with the database (I have to initialize it, but I don't know how yet), but I think I will find the solution by myself. Thanks
